# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mews/Documents/repos/DiligentEngine/DiligentSamples/Tutorials/Tutorial04_Instancing/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/FindOpenGL.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/FindPackageMessage.cmake))

/Users/mews/Documents/repos/DiligentEngine/build/MacOS/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/bin/cmake -S/Users/mews/Documents/repos/DiligentEngine -B/Users/mews/Documents/repos/DiligentEngine/build/MacOS
